apiVersion: server.eidolonai.com/v1alpha1
kind: Reference
metadata:
  name: OpenAIConnectionHandler
spec:
  implementation: AzureOpenAIConnectionHandler
  base_url: https://eidolon-azure.openai.azure.com/openai
  azure_ad_token_provider: null